# Generated by Django 6.0.3 on 2026-03-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.PositiveIntegerField(unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tingkat', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Kabupaten',
                'db_table': 'kabupaten',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.PositiveIntegerField(unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tingkat', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
                'db_table': 'provinsi',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.PositiveIntegerField(unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tingkat', models.PositiveSmallIntegerField(default=3)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan', to='wilayah.kabupaten')),
            ],
            options={
                'verbose_name_plural': 'Kecamatan',
                'db_table': 'kecamatan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.PositiveIntegerField(unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tingkat', models.PositiveSmallIntegerField(default=4)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desa', to='wilayah.kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Desa',
                'db_table': 'desa',
                'ordering': ['kode'],
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupaten', to='wilayah.provinsi'),
        ),
    ]
